### ISSUE TITLE
Some websites trigger access to specific passwords

### ISSUE THREAD

**Issue by rugk** [smorks/keepasshttp-connector#63]
It is really strange and potentially a security issue as for some websites I see that KeePassHttpConnector requests some passwords, which are completely unrelated… (There is not even a visible password field…)

I'll let you know next time when I see a website, where this happens. Cannot remember which websites it affects.

**Comment by rugk** [comment]
Ah e.g. this site https://eventphone.de/guru2/signup requests my password for a [gittea](https://github.com/go-gitea/gitea) instance. Even worse,. it actually fills in the password!

So for sure, this is a security issue!

**Comment by smorks** [comment]
Turn off "Automatically fill-in single credentials entry", and it won't auto-fill anything.

It's hard for me to say why this is happening. i went to both the login & signup page, and it didn't bring up any of my existing credentials. could you post screenshots (with credentials blacked out) of the gitea entry that's it's bringing up?

**Comment by rugk** [comment]
> Turn off "Automatically fill-in single credentials entry", and it won't auto-fill anything.

That is not a solution, I want that feature, of course. It just chooses the wrong website.

**Comment by rugk** [comment]
![grafik](https://user-images.githubusercontent.com/11966684/34318996-9f567d0e-e7d5-11e7-8ad6-3175d6ab4a35.png)

BTW, after I've created an account there, and saved a new password, it fills in the right one and does not even offer me the "wrong" one again…

**Comment by rugk** [comment]
![grafik](https://user-images.githubusercontent.com/11966684/34319003-d1a0df02-e7d5-11e7-945a-426fc6daf405.png)

**Comment by smorks** [comment]
sorry, i never said that option was a solution, i was just trying to help.

anyways, this is most likely a problem in KeePassXC. all this extension does is send the url (and the form submit url) to KeePassXC, and it does the matching. what version are you running? i know there was a bug that they fixed in v2.2.2: keepassxreboot/keepassxc#1017

**Comment by rugk** [comment]
v2.2.2

**Comment by rugk** [comment]
Still reproducible with v2.2.4 BTW, see https://github.com/keepassxreboot/keepassxc/issues/1017#issuecomment-354624356
